### ISSUE TITLE
Improve CI/CD permissions

### ISSUE THREAD

**Issue by DavideSegullo** [nabla-studio/nablajs#17]
We should add the following configuration inside [ci.yml](https://github.com/nabla-studio/nablajs/blob/next/.github/workflows/ci.yml#L3):
```yml
permissions:
 actions: write
 deployments: write
 packages: write
 pull-requests: write
 issues: write
```

This will prevente the following error inside the semantic release plugin for github:
```bash
[@semantic-release/github] › ✖  Not allowed to add a comment to the issue #15.
```
